return {
	{ label = "1 Second",   value = 1, },
	{ label = "2 Seconds",  value = 2, },
	{ label = "3 Seconds",  value = 3, },
	{ label = "4 Seconds",  value = 4, },
	{ label = "5 Seconds",  value = 5, },
	{ label = "6 Seconds",  value = 6, },
	{ label = "7 Seconds",  value = 7, },
	{ label = "8 Seconds",  value = 8, },
	{ label = "10 Seconds", value = 10,},
	{ label = "12 Seconds", value = 12,},
	{ label = "15 Seconds", value = 15,},
	{ label = "18 Seconds", value = 18,},
	{ label = "20 Seconds", value = 20,},
	{ label = "25 Seconds", value = 25,},
	{ label = "30 Seconds", value = 30,},
	{ label = "40 Seconds", value = 40,},
	{ label = "50 Seconds", value = 50,},
	{ label = "60 Seconds", value = 60,},
}
