return {
	{ key = "a", value = { quad = { x = 776, y =  24, w = 15, h = 16 }, } },
	{ key = "b", value = { quad = { x = 800, y =  24, w = 15, h = 16 }, } },
	{ key = "c", value = { quad = { x = 824, y =  24, w = 15, h = 16 }, } },
	{ key = "d", value = { quad = { x = 848, y =  24, w = 15, h = 16 }, } },
	{ key = "e", value = { quad = { x = 872, y =  24, w = 14, h = 16 }, } },
	{ key = "f", value = { quad = { x = 896, y =  24, w = 14, h = 16 }, } },
	{ key = "g", value = { quad = { x = 776, y =  48, w = 16, h = 16 }, } },
	{ key = "h", value = { quad = { x = 800, y =  48, w = 15, h = 16 }, } },
	{ key = "i", value = { quad = { x = 825, y =  48, w = 6 , h = 16 }, } },
  --{ key = "j", value = { quad = {                                  }, } },
	{ key = "k", value = { quad = { x = 840, y =  48, w = 16, h = 16 }, } },
	{ key = "l", value = { quad = { x = 864, y =  48, w = 15, h = 16 }, } },
	{ key = "m", value = { quad = { x = 888, y =  48, w = 16, h = 16 }, } },
	{ key = "n", value = { quad = { x = 776, y =  72, w = 15, h = 16 }, } },
	{ key = "o", value = { quad = { x = 800, y =  72, w = 16, h = 16 }, } },
	{ key = "p", value = { quad = { x = 824, y =  72, w = 15, h = 16 }, } },
  --{ key = "q", value = { quad = {                                  }, } },
	{ key = "r", value = { quad = { x = 848, y =  72, w = 15, h = 16 }, } },
	{ key = "s", value = { quad = { x = 873, y =  72, w = 14, h = 16 }, } },
	{ key = "t", value = { quad = { x = 896, y =  71, w = 14, h = 16 }, } },
	{ key = "u", value = { quad = { x = 776, y =  96, w = 15, h = 16 }, } },
  --{ key = "v", value = { quad = {                                  }, } },
  --{ key = "w", value = { quad = {                                  }, } },
  --{ key = "x", value = { quad = {                                  }, } },
	{ key = "y", value = { quad = { x = 800, y =  96, w = 15, h = 16 }, } },
	{ key = "z", value = { quad = { x = 824, y =  96, w = 15, h = 16 }, } },
	{ key = ".", value = { quad = { x = 849, y = 109, w =  3, h = 3  }, } },

  -- "@" is a shortcut for "ACT"
	{ key = "@", value = { quad = { x = 864, y = 104, w = 24, h = 8  }, } },
  --{ key = "0", value = { quad = {                                  }, } },
	{ key = "1", value = { quad = { x = 924, y =  24, w = 7 , h = 24 }, } },
	{ key = "2", value = { quad = { x = 921, y =  56, w = 14, h = 24 }, } },
	{ key = "3", value = { quad = { x = 921, y =  88, w = 14, h = 24 }, } },
  --{ key = "4", value = { quad = {                                  }, } },
  --{ key = "5", value = { quad = {                                  }, } },
  --{ key = "6", value = { quad = {                                  }, } },
  --{ key = "7", value = { quad = {                                  }, } },
  --{ key = "8", value = { quad = {                                  }, } },
  --{ key = "9", value = { quad = {                                  }, } },

  -- "*" is a shortcut for the spotlight
	{ key = "*", value = { quad = { x = 944, y =  24, w = 56, h = 56 }, } },
}
