return {
    { key = "a", value = { quad = { x = 352, y = 896, w = 16, h = 16 }, } },
  --{ key = "b", value = { quad = {                                  }, } },
    { key = "c", value = { quad = { x = 400, y = 896, w = 16, h = 16 }, } },
  --{ key = "d", value = { quad = {                                  }, } },
  --{ key = "e", value = { quad = {                                  }, } },
  --{ key = "f", value = { quad = {                                  }, } },
    { key = "g", value = { quad = { x = 496, y = 896, w = 16, h = 16 }, } },
  --{ key = "h", value = { quad = {                                  }, } },
  --{ key = "i", value = { quad = {                                  }, } },
    { key = "j", value = { quad = { x = 352, y = 920, w = 15, h = 16 }, } },
  --{ key = "k", value = { quad = {                                  }, } },
  --{ key = "l", value = { quad = {                                  }, } },
    { key = "m", value = { quad = { x = 424, y = 920, w = 20, h = 16 }, } },
  --{ key = "n", value = { quad = {                                  }, } },
    { key = "o", value = { quad = { x = 480, y = 920, w = 16, h = 16 }, } },
  --{ key = "p", value = { quad = {                                  }, } },
    { key = "q", value = { quad = { x = 528, y = 920, w = 16, h = 16 }, } },
  --{ key = "r", value = { quad = {                                  }, } },
    { key = "s", value = { quad = { x = 352, y = 944, w = 14, h = 16 }, } },
    { key = "t", value = { quad = { x = 376, y = 944, w = 16, h = 16 }, } },
    { key = "u", value = { quad = { x = 400, y = 944, w = 16, h = 16 }, } },
    { key = "v", value = { quad = { x = 424, y = 944, w = 16, h = 16 }, } },
    { key = "w", value = { quad = { x = 448, y = 944, w = 20, h = 16 }, } },
    { key = "x", value = { quad = { x = 480, y = 944, w = 16, h = 16 }, } },
    { key = "y", value = { quad = { x = 504, y = 944, w = 16, h = 16 }, } },
    { key = "z", value = { quad = { x = 528, y = 944, w = 16, h = 16 }, } },
    { key = "2", value = { quad = { x = 552, y = 944, w = 15, h = 16 }, } },
}
