return {
	{ key = "SCORE",    value = { quad = { x =  25, y = 433, w = 39, h =  11 }, } },
	{ key = "TIME",     value = { quad = { x =  25, y = 457, w = 31, h =  11 }, } },
	{ key = "RINGS",    value = { quad = { x =  25, y = 481, w = 39, h =  11 }, } },
	{ key = "RING",     value = { quad = { x = 365, y = 481, w = 31, h =  11 }, } },
	{ key = "BONUS",    value = { quad = { x = 404, y = 457, w = 40, h =  11 }, } },
	{ key = "TEMPLATE", value = { quad = { x =  40, y = 208, w = 96, h = 208 }, } },
  
  --{ key = "b", value = { quad = {                                  }, } },
  --{ key = "c", value = { quad = {                                  }, } },
  --{ key = "e", value = { quad = {                                  }, } },
  --{ key = "g", value = { quad = {                                  }, } },
  --{ key = "i", value = { quad = {                                  }, } },
  --{ key = "m", value = { quad = {                                  }, } },
  --{ key = "n", value = { quad = {                                  }, } },
  --{ key = "o", value = { quad = {                                  }, } },
  --{ key = "r", value = { quad = {                                  }, } },
  --{ key = "s", value = { quad = {                                  }, } },
  --{ key = "t", value = { quad = {                                  }, } },
  --{ key = "u", value = { quad = {                                  }, } },

	{ key = "0", value = { quad = { x = 73, y = 433, w = 7, h = 11 }, } },
	{ key = "1", value = { quad = { x = 90, y = 433, w = 4, h = 11 }, } },
	{ key = "2", value = { quad = { x = 105, y = 433, w = 7, h = 11 }, } },
	{ key = "3", value = { quad = { x = 121, y = 433, w = 7, h = 11 }, } },
  	{ key = "4", value = { quad = { x = 137, y = 433, w = 7, h = 11 }, } },
	{ key = "5", value = { quad = { x = 153, y = 433, w = 7, h = 11 }, } },
	{ key = "6", value = { quad = { x = 169, y = 433, w = 7, h = 11 }, } },
	{ key = "7", value = { quad = { x = 185, y = 433, w = 7, h = 11 }, } },
	{ key = "8", value = { quad = { x = 201, y = 433, w = 7, h = 11 }, } },
	{ key = "9", value = { quad = { x = 217, y = 433, w = 7, h = 11 }, } },
}
