return {
  properties = {
      music = "Green Hill Zone",
      musicVolume = 0.4,
      musicPitch = 1.1,
      musicEffect = "Echo",
      musicDelay = 0.2,
      musicStrength = 0.6,
      musicEchoCount = 5,
      sounds = {
          vanish = {
              volume = 0.7,
              pitch = 1.2,
              sound = "vanish",
              audioEffect = "Reverb",
              reverse = false,
              delay = 0.3,
          },
          sonicHit = {
              volume = 1,
              detuning = 1,
              pitch = 1,
              sound = "klankOuch",
              audioEffect = "Echo",
              reverse = true,
              delay = 0.2,
          },
          badnikHit = {
              volume = 0.6,
              echoCount = 3,
              strength = 0.2,
              pitch = 1.1,
              delay = 0.2,
              audioEffect = "Echo",
              reverse = false,
              sound = "badnikDeath",
          },
          ballThud = {
              volume = 1,
              echoCount = 4,
              delay = 0.1,
              pitch = 1.1,
              sound = "thud",
              audioEffect = "Echo",
              strength = 0.5,
              detuning = 1,
          },
          badnikFalling = {
              volume = 1,
              echoCount = 3,
              strength = 0.6,
              pitch = 1.65,
              delay = 0.2,
              audioEffect = "Echo",
              reverse = false,
              sound = "yaaaaah",
          },
          badnikSquished = {
              strength = 1,
              echoCount = 4,
              audioEffect = "Echo",
              reverse = false,
              sound = "smoosh",
              volume = 1,
              pitch = 1,
              detuning = 1,
              delay = 0,
          },
          jumping = {
              volume = 0.9,
              echoCount = 1,
              pitch = 1,
              sound = "sonicCDJumping",
              audioEffect = "Reverb",
              reverse = false,
              delay = 0.3,
          },
          badnikStrike = {
              strength = 1,
              echoCount = 3,
              pitch = 1.1,
              sound = "bowlingStrike",
              audioEffect = "Echo",
              volume = 1,
              delay = 0,
          },
          collectOddRing = {
              volume = 1,
              pitch = 1.25,
              sound = "ringCollectL",
          },
          braking = {
              volume = 1,
              echoCount = 2,
              strength = 0.5,
              pitch = 1.15,
              delay = 0.3,
              audioEffect = "Reverb",
              reverse = false,
              sound = "sneakers",
          },
          collectEvenRing = {
              volume = 1,
              pitch = 1,
              reverse = false,
              sound = "ringCollectR",
          },
          giantRing = {
              strength = 0.4,
              echoCount = 6,
              pitch = 1.25,
              sound = "giantRing",
              audioEffect = "Echo",
              volume = 0.5,
              delay = 0.2,
          },
      },
  },
  { row = 3, data = { {}, { "ghzChunks", 10}, { "ghzChunks", 10}, { "ghzChunks", 10}, { "ghzChunks", 10}, } },
  { row = 7, data = { {}, { "scdPtpChunks", 1}, { "scdPtpChunks", 7}, { "scdPtpChunks", 6}, { "scdPtpChunks", 3}, { "scdPtpChunks", 3, xFlip = true}, {}, } },
  { row = 8, data = { {}, { "scdPtpChunks", 5, xFlip = true}, { "scdPtpChunks", 5}, { "scdPtpChunks", 5, xFlip = true}, { "scdPtpChunks", 5}, { "scdPtpChunks", 5, xFlip = true}, { "scdPtpChunks", 6}, { "scdPtpChunks", 7}, { "scdPtpChunks", 2}, { "scdPtpChunks", 3}, {}, } },
  { row = 9, data = { {}, { "scdPtpChunks", 5}, { "scdPtpChunks", 5, xFlip = true}, { "scdPtpChunks", 5}, { "scdPtpChunks", 5, xFlip = true}, { "scdPtpChunks", 5}, { "scdPtpChunks", 5, xFlip = true}, { "scdPtpChunks", 5}, { "scdPtpChunks", 5, xFlip = true}, { "scdPtpChunks", 5}, {}, } },
  { row = 11, data = { {}, {}, { "scdCCPastChunksOrig", 4}, {}, } },
  { row = 14, data = { {}, {}, {}, {}, {}, {}, {}, { "scdPtpChunks", 3}, {}, { "scdPtpChunks", 4}, { "scdPtpChunks", 6, xFlip = true}, } },
  { row = 15, data = { {}, {}, {}, {}, {}, {}, { "ghzChunks", 23}, { "ghzChunks", 17}, { "ghzChunks", 24}, { "scdPtpChunks", 5}, { "scdPtpChunks", 5}, {}, } },
  { row = 16, data = { {}, {}, {}, { "ghzChunks", 10}, { "ghzChunks", 19}, { "ghzChunks", 10}, { "ghzChunks", 37}, { "ghzChunks", 7}, { "ghzChunks", 35}, { "scdPtpChunks", 5}, { "scdPtpChunks", 5}, } },
  { row = 17, data = { {}, {}, { "ghzChunks", 10}, { "ghzChunks", 34}, { "ghzChunks", 37}, { "ghzChunks", 7}, { "ghzChunks", 7}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, {}, } },
  { row = 18, data = { {}, {}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, {}, } },
  { row = 21, data = { {}, {}, {}, {}, {}, { "ghzChunks", 10}, { "ghzChunks", 19}, { "ghzChunks", 19}, { "ghzChunks", 37}, { "ghzChunks", 7}, { "ghzChunks", 20}, { "ghzChunks", 13}, { "ghzChunks", 23}, { "ghzChunks", 24}, { "ghzChunks", 24, xFlip = true}, { "ghzChunks", 25}, { "ghzChunks", 25}, { "ghzChunks", 23, xFlip = true}, {}, } },
  { row = 22, data = { {}, {}, { "ghzChunks", 13}, { "ghzChunks", 23}, { "ghzChunks", 25}, { "ghzChunks", 37}, { "ghzChunks", 7}, { "ghzChunks", 7}, { "ghzChunks", 7}, { "ghzChunks", 37, xFlip = true}, { "ghzChunks", 34}, { "ghzChunks", 34}, { "ghzChunks", 34}, { "ghzChunks", 35}, { "ghzChunks", 35, xFlip = true}, { "ghzChunks", 34}, { "ghzChunks", 37}, { "ghzChunks", 7}, { "ghzChunks", 20}, { "ghzChunks", 13}, { "ghzChunks", 23}, {}, } },
}
