return {
  properties = {
      music = "Green Hill Zone",
      musicVolume = 1.45,
      musicPitch = 1.1,
      musicDelay = 0.2,
      musicStrength = 0.5,
      musicEchoCount = 3,
      sounds = {
          jumping = {
              reverse = false,
              delay = 0.3,
              volume = 0.9,
              pitch = 1,
              sound = "sonicCDJumping",
              audioEffect = "Reverb",
              echoCount = 1,
          },
          pushObject = {
              sound = "pushRock",
              reverse = false,
              strength = 0.3,
              pitch = 1,
              volume = 0.7,
              detuning = 1,
              delay = 0.1,
              audioEffect = "Echo",
              echoCount = 2,
          },
          badnikStrike = {
              delay = 0,
              strength = 1,
              volume = 1,
              audioEffect = "Echo",
              sound = "bowlingStrike",
              pitch = 1.1,
              echoCount = 3,
          },
          collectEvenRing = {
              reverse = false,
              sound = "ringCollectR",
              pitch = 1,
              volume = 1,
          },
          postLamp = {
              sound = "ohYeahDeep",
              reverse = false,
              strength = 0.7,
              pitch = 1.45,
              volume = 2,
              detuning = 1,
              delay = 0.5,
              audioEffect = "None",
              echoCount = 2,
          },
          vanish = {
              reverse = false,
              volume = 0.7,
              delay = 0.3,
              sound = "vanish",
              audioEffect = "Reverb",
              pitch = 1.2,
          },
          sonicHit = {
              reverse = true,
              delay = 0.2,
              volume = 1,
              detuning = 1,
              sound = "klankOuch",
              pitch = 1,
              audioEffect = "Echo",
          },
          badnikHit = {
              reverse = false,
              delay = 0.2,
              strength = 0.2,
              volume = 0.6,
              pitch = 1.1,
              sound = "badnikDeath",
              audioEffect = "Echo",
              echoCount = 3,
          },
          collectOddRing = {
              sound = "ringCollectL",
              pitch = 1.25,
              volume = 1,
          },
          ballThud = {
              delay = 0.1,
              pitch = 1.1,
              strength = 0.5,
              volume = 1,
              detuning = 1,
              sound = "thud",
              audioEffect = "Echo",
              echoCount = 4,
          },
          giantRing = {
              delay = 0.2,
              strength = 0.4,
              volume = 0.5,
              audioEffect = "Echo",
              sound = "giantRing",
              pitch = 1.25,
              echoCount = 6,
          },
          lampPost = {
              reverse = false,
              delay = 0.1,
              volume = 0.9,
              pitch = 1,
              sound = "lampPost",
              audioEffect = "Echo",
              echoCount = 2,
          },
          badnikFalling = {
              sound = "yaaaaah",
              reverse = false,
              strength = 1,
              pitch = 1.65,
              volume = 1,
              detuning = 1,
              delay = 0,
              audioEffect = "Echo",
              echoCount = 5,
          },
          badnikSquished = {
              sound = "smoosh",
              reverse = false,
              strength = 1,
              pitch = 1,
              volume = 1,
              detuning = 1,
              delay = 0,
              audioEffect = "Echo",
              echoCount = 4,
          },
          braking = {
              reverse = false,
              delay = 0.3,
              strength = 0.5,
              volume = 1,
              pitch = 1.15,
              sound = "sneakers",
              audioEffect = "Reverb",
              echoCount = 2,
          },
      },
      time = {
          timeAtStart = 600,
          timeLabel = "time to go",
      },
  },
  { row = 1, data = { { "ghzChunks", 25}, { "ghzChunks", 24}, { "ghzChunks", 17}, {}, } },
  { row = 2, data = { { "ghzChunks", 17}, { "ghzChunks", 39}, { "ghzChunks", 17}, {}, } },
  { row = 3, data = { { "ghzChunks", 17}, { "ghzChunks", 35}, { "ghzChunks", 34}, { "ghzChunks", 10}, { "ghzChunks", 10}, {}, } },
  { row = 5, data = { {}, {}, {}, {}, { "scdPtpGF1Chunks", 74}, { "scdPtpGF1Chunks", 75}, { "scdPtpGF1Chunks", 72}, { "scdPtpGF1Chunks", 75}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, { "ghzChunks", 13}, { "ghzChunks", 23}, { "ghzChunks", 25}, { "ghzChunks", 24}, { "ghzChunks", 23}, { "ghzChunks", 25}, { "ghzChunks", 23, xFlip = true}, {}, } },
  { row = 6, data = { {}, {}, {}, {}, { "scdPtpGF1Chunks", 80}, { "scdPtpGF1Chunks", 80}, { "scdPtpGF1Chunks", 80}, { "scdPtpGF1Chunks", 47}, {}, {}, {}, {}, { "ghzChunks", 10}, { "ghzChunks", 19}, { "ghzChunks", 20}, { "ghzChunks", 4}, { "ghzChunks", 20}, { "ghzChunks", 13}, { "ghzChunks", 23}, { "ghzChunks", 25}, { "ghzChunks", 27, xFlip = true}, { "ghzChunks", 37, xFlip = true}, { "ghzChunks", 34}, { "ghzChunks", 35}, { "ghzChunks", 34}, { "ghzChunks", 37}, { "ghzChunks", 7}, { "ghzChunks", 4}, } },
  { row = 7, data = { {}, { "scdPtpChunks", 1}, { "scdPtpChunks", 7}, { "scdPtpChunks", 6}, { "scdPtpChunks", 3}, { "scdPtpChunks", 3, xFlip = true}, {}, {}, {}, {}, {}, {}, { "ghzChunks", 34}, { "ghzChunks", 34}, { "ghzChunks", 34}, { "ghzChunks", 35}, { "ghzChunks", 34}, { "ghzChunks", 37}, { "ghzChunks", 7}, { "ghzChunks", 27}, { "ghzChunks", 28}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 35}, { "ghzChunks", 10}, {}, } },
  { row = 8, data = { {}, { "scdPtpChunks", 5, xFlip = true}, { "scdPtpChunks", 5}, { "scdPtpChunks", 5, xFlip = true}, { "scdPtpChunks", 5}, { "scdPtpChunks", 5, xFlip = true}, { "scdPtpChunks", 6}, { "scdPtpChunks", 7}, { "scdPtpChunks", 2}, { "scdPtpChunks", 3}, {}, } },
  { row = 9, data = { {}, { "scdPtpChunks", 5}, { "scdPtpChunks", 5, xFlip = true}, { "scdPtpChunks", 5}, { "scdPtpChunks", 5, xFlip = true}, { "scdPtpChunks", 5}, { "scdPtpChunks", 5, xFlip = true}, { "scdPtpChunks", 5}, { "scdPtpChunks", 5, xFlip = true}, { "scdPtpChunks", 5}, {}, { "scdCCPastChunksOrig", 4}, {}, } },
  { row = 10, data = { {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, { "scdCCPastChunksOrig", 4, xFlip = true}, {}, } },
  { row = 11, data = { {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, { "scdPtpGF1Chunks", 74}, { "scdPtpGF1Chunks", 75}, { "scdPtpGF1Chunks", 72}, { "scdPtpGF1Chunks", 74}, } },
  { row = 12, data = { {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, { "scdPtpGF1Chunks", 80}, { "scdPtpGF1Chunks", 80}, { "scdPtpGF1Chunks", 80}, { "scdPtpGF1Chunks", 47}, {}, {}, {}, {}, {}, { "scdCCPastChunksOrig", 4}, {}, } },
  { row = 13, data = { {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, { "scdPtpChunksOrig", 30, xFlip = true}, { "scdPtpChunksOrig", 30}, {}, { "scdCCPastChunksOrig", 5}, {}, } },
  { row = 14, data = { {}, {}, {}, {}, {}, {}, {}, { "scdPtpChunks", 3}, {}, { "scdPtpChunks", 4}, { "scdPtpChunks", 6, xFlip = true}, { "scdPtpChunksOrig", 63}, { "scdPtpChunksOrig", 63}, } },
  { row = 15, data = { {}, {}, {}, {}, {}, {}, { "ghzChunks", 23}, { "ghzChunks", 17}, { "ghzChunks", 24}, { "scdPtpChunks", 5}, { "scdPtpChunks", 5}, { "scdPtpChunksOrig", 63}, { "scdPtpChunksOrig", 63}, {}, } },
  { row = 16, data = { {}, {}, {}, { "ghzChunks", 10}, { "ghzChunks", 19}, { "ghzChunks", 10}, { "ghzChunks", 37}, { "ghzChunks", 7}, { "ghzChunks", 35}, { "scdPtpChunks", 5}, { "scdPtpChunks", 5}, { "scdPtpChunksOrig", 63}, {}, { "scdCCPastChunksOrig", 4}, {}, {}, {}, { "scdCCPastChunksOrig", 5}, {}, } },
  { row = 17, data = { {}, {}, { "ghzChunks", 10}, { "ghzChunks", 34}, { "ghzChunks", 37}, { "ghzChunks", 7}, { "ghzChunks", 7}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, {}, } },
  { row = 18, data = { {}, {}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, { "ghzChunks", 17}, {}, {}, {}, {}, {}, {}, {}, {}, { "scdCCPastChunksOrig", 4}, {}, } },
  { row = 20, data = { {}, {}, {}, {}, {}, {}, {}, {}, { "ghzChunks", 19}, { "ghzChunks", 10}, } },
  { row = 21, data = { {}, {}, {}, {}, {}, { "ghzChunks", 10}, { "ghzChunks", 19}, { "ghzChunks", 19}, { "ghzChunks", 37}, { "ghzChunks", 7}, { "ghzChunks", 20}, { "ghzChunks", 13}, { "ghzChunks", 23}, { "ghzChunks", 24}, { "ghzChunks", 24, xFlip = true}, { "ghzChunks", 25}, { "ghzChunks", 25}, { "ghzChunks", 23, xFlip = true}, {}, } },
  { row = 22, data = { {}, { "ghzChunks", 19}, { "ghzChunks", 13}, { "ghzChunks", 23}, { "ghzChunks", 25}, { "ghzChunks", 37}, { "ghzChunks", 7}, { "ghzChunks", 7}, { "ghzChunks", 7}, { "ghzChunks", 37, xFlip = true}, { "ghzChunks", 34}, { "ghzChunks", 34}, { "ghzChunks", 34}, { "ghzChunks", 35}, { "ghzChunks", 35, xFlip = true}, { "ghzChunks", 34}, { "ghzChunks", 37}, { "ghzChunks", 7}, { "ghzChunks", 20}, { "ghzChunks", 13}, { "ghzChunks", 23}, } },
}
